---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubernetes-external-secrets-helm-repository
  namespace: kubernetes-external-secrets
spec:
  interval: 30s
  url: https://external-secrets.github.io/kubernetes-external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-external-secrets
  namespace: kubernetes-external-secrets
spec:
  interval: 30s
  releaseName: kubernetes-external-secrets
  targetNamespace: kubernetes-external-secrets
  chart:
    spec:
      interval: 30s
      chart: kubernetes-external-secrets
      version: 8.5.5
      sourceRef:
        kind: HelmRepository
        name: kubernetes-external-secrets-helm-repository
        namespace: kubernetes-external-secrets
  values:
    env:
      POLLER_INTERVAL_MILLISECONDS: 20000
      LOG_LEVEL: info
