---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets-helm-repository
  namespace: external-secrets
spec:
  interval: 30s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30s
  releaseName: external-secrets
  targetNamespace: external-secrets
  chart:
    spec:
      interval: 30s
      chart: external-secrets
      version: 0.9.9
      sourceRef:
        kind: HelmRepository
        name: external-secrets-helm-repository
        namespace: external-secrets
  values:
    env:
      POLLER_INTERVAL_MILLISECONDS: 20000
      LOG_LEVEL: info
