name: Renovate

on:
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v39.0.5
      with:
        renovate-version: 36.107.1
        token: ${{ secrets.RENOVATE_TOKEN }}